### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by anupvarghese**
- Update react
- Update redux
- Update radium

### CODE REVIEW

**Comment by johndagostino** [comment]
Fixes #5

**Comment by jakubkottnauer** [comment]
Thanks for the PR and sorry for not getting back to you earlier. I don't think there's a reason to put `lib` in the repo and be so restrictive about dependency versions. I've just pushem them in a separate commit because I needed them in a new project as well. I'll be happy to merge to rest if you fix it.

**Comment by anupvarghese** [comment]
@jakubkottnauer yup, `lib` was added to run it separately at my end. Removed it now. Thanks

**Comment by jakubkottnauer** [comment]
Cool, please remove the changes from package.json as well (the version in master should be ok now), squash the commits and I'll merge it :)

**Comment by anupvarghese** [comment]
@jakubkottnauer Yeah, noticed that.. done now

**Pull request closed without merging**
